### ISSUE TITLE
Build script should use production rawgit cdn

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/howto-components#102]
Half baked note. I was looking at the output from building the elements for webfundamentals and noticed it's using dev rawgit cdn urls instead of production ones. Not sure where these get inserted but wanted to note that we should change this.

**Comment by robdodson** [comment]
Using the webcomponents shadow dom + custom elements build
https://cdn.rawgit.com/webcomponents/webcomponentsjs/d5b7ca65/webcomponents-sd-ce.js

**Comment by surma** [comment]
Close if #103 lands
