### ISSUE TITLE
The `hasOwnProperty` check in `_upgradeProperty` fails if a property is only defined through its getter/setter

### ISSUE THREAD

**Issue by ciampo** [GoogleChrome/howto-components#116]
Hello,

I've been trying to implement the lazy properties pattern in a Custom Element I'm working on.

I'm using the `_upgradeProperty` function from `<howto-checkbox>`, and I noticed that the `hasOwnProperty` check returns `false` for properties that are defined only through getters/setters.

Am I missing something about the way the lazy properties pattern works?

**Comment by surma** [comment]
The lazy property pattern is supposed to cover a very specific corner case of custom elements. Here’s the scenario:

```html
<!doctype html>
<my-element id="a"></my-element>
<script src="someFramework.js"></script>
<script src="my-element.js"></script>
```

Notice how `someFramework.js` is included (and executed!) *before* `my-element.js`, which contains the definition for `<my-element>`. While `someFramework.js` executes, `#a` will be a generic `HTMLElement` and not `MyElement`, as the element’s definition has not been loaded yet.  If, during that initial execution, `someFramework.js` sets property `x` on `#a`, the DOM object will have a property `x`. If `x` is a setter on `MyElement`, the element needs to ingest that property on its DOM object and trigger the setter manually to not lose the value that has been set. And that’s exactly what `_upgradeProperty` does.

Does this help?

**Comment by ciampo** [comment]
Yes it does, thanks! I have then another question:

Let's say that I have an attribute `x` on my Custom Element. When modified, as a side effect, this attribute triggers some changes in the shadow DOM — I grab references to those elements in the shadow DOM in the `connectedCallback`.

Now, let's imagine this scenario: 
```html
<!doctype html>
<script src="my-element.js"></script>
<my-element x="some_initial_value"></my-element>
```

In my case, I find that `attributeChangedCallbackc` fires for the attribute `x` before I can gran any reference to the Shadow DOM, and therefore, I can't make those internal changes related to that attribute. I thought that the `_upgradeProperty()` function could help me in "forcing" those updates, but I guess I was wrong.

At the moment, I'm just doing `this.x = this.x` in the `connectedCallback` and, although it works, it seems a bit too hacky. Do you suggest any other approach to solve this problem?

**Comment by robdodson** [comment]
Have you tried creating the contents of your Shadow DOM in the element's constructor instead? Here's an example: https://jsbin.com/dahokeb/2/edit?html,output

The order of lifecycle callbacks should go:

```
constructor
attributeChangedCallback
connectedCallback
```

**Comment by ciampo** [comment]
Hey @robdodson,

your suggestion did indeed work! For some reason I never thought it was a good practice to `querySelector` the shadow dom in the `constructor`.

Thanks a lot to both you and @surma for the quick answers. It would be good if later on you could have a look at the CE I'm coding and see if there's anything I can improve.

**Comment by robdodson** [comment]
Yeah there's a tricky distinction there. As I understand it, you're allowed to do pretty much whatever you want inside of your shadow root in the constructor. But you're not allowed to touch the Light DOM in any way.
