### ISSUE TITLE
[Docs]: Google page for howto components has no links to this repo

### ISSUE THREAD

**Issue by dmitriid** [GoogleChrome/howto-components#117]
When searching "howto-components webcompnents" you will land here: https://developers.google.com/web/fundamentals/architecture/building-components/examples/

There are no links to this repo to see code, contribute, view issues etc.

**Comment by surma** [comment]
That’s somewhat intentional – at least for now. The section on WebFundamentals is supposed to be a stand-alone documentation that can be read. 

The elements the are in the examples section have their code embedded and explained in the corresponding article.

**Comment by dmitriid** [comment]
@surma I understand that. However, developers are quite used to seeing links to repos, and certain things like #112 can only be found by searching issues, for example.

**Comment by dmitriid** [comment]
UPD: I realised another reason to have a link to repo: to see the code as-is, not in "literate style", because it's quite confusing, see #118
