### ISSUE TITLE
Convert to es6 IIFEs?

### ISSUE THREAD

**Issue by priley86** [GoogleChrome/howto-components#128]
https://github.com/GoogleChromeLabs/howto-components/blob/079d0fa34ff9038b26ea8883b1db5dd6b677d7ba/elements/howto-toggle-button/howto-toggle-button.js#L16

Curious how the IFFE style was decide upon? i.e. using:
```
(function() {
```
vs
```
;(() => {
```
Seems to be pretty comparable performance and this is equally supported now - no?
https://jsperf.com/iffe-es5-es6

**Comment by surma** [comment]
I have never really considered using Far Arrow Functions (FAFs) for IIFE, but I’ll do that now 😄 

**Pros:**
- Saving a couple of bytes 

**Cons:**
- Confusing to people not too familiar with FAFs (even to me it looks more like a random series of symbols than a readable expression)
- Potential foot gun if `this` ever comes into play

Anything you’d like to see added to the list? 

Honestly, I don’t see a lot of reason to have a strong opinion here. Ideally we’d be using ES6 modules anyways, so we could drop the IIFE altogether.

**Comment by priley86** [comment]
+1 for ES6 modules. I'm perfectly OK with waiting for this if that is the preference!

Just saw the old IIFE syntax and was a bit confused given the other ES6. I'll close this issue given the understanding you are moving to modules soon!
