### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by arunsoman** [GoogleChrome/howto-components#132]
npm install               
npm WARN package.json howto-components@0.0.1 No repository field.

npm run build                

> howto-components@0.0.1 build /home/arun/WebstormProjects/web-component/howto-components
> mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js

/home/arun/WebstormProjects/web-component/howto-components/build-documentation.js:77
    .then(([code, demo]) => {
           ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

npm ERR! Linux 4.4.104-39-default
npm ERR! argv "/usr/bin/node4" "/usr/bin/npm-default" "run" "build"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! howto-components@0.0.1 build: `mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the howto-components@0.0.1 build script 'mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js'.
npm ERR! This is most likely a problem with the howto-components package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs howto-components
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls howto-components
npm ERR! There is likely additional logging output above.

============================
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node4', '/usr/bin/npm-default', 'run', 'build' ]
2 info using npm@2.15.11
3 info using node@v4.8.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild howto-components@0.0.1
6 info build howto-components@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info howto-components@0.0.1 Failed to exec build script
9 verbose stack Error: howto-components@0.0.1 build: `mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm4/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm4/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid howto-components@0.0.1
11 verbose cwd /home/arun/WebstormProjects/web-component/howto-components
12 error Linux 4.4.104-39-default
13 error argv "/usr/bin/node4" "/usr/bin/npm-default" "run" "build"
14 error node v4.8.7
15 error npm  v2.15.11
16 error code ELIFECYCLE
17 error howto-components@0.0.1 build: `mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js`
17 error Exit status 1
18 error Failed at the howto-components@0.0.1 build script 'mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js'.
18 error This is most likely a problem with the howto-components package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     mkdir -p docs/scripts && cp node_modules/@webcomponents/webcomponentsjs/webcomponents-sd-ce.js docs/scripts/ && node build-documentation.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs howto-components
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls howto-components
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by surma** [comment]
Your are running Node 4 which is an extremely old version. Please update to the current stable LTS of Node (Node 8).
