### ISSUE TITLE
[Question] HowTo-Components vs Polymer Components Library

### ISSUE THREAD

**Issue by MeTaNoV** [GoogleChrome/howto-components#71]
Hi,
I am really curious about the goal of such example library which seems to be fully focused on Javascipt ES6.
Do you pave the way to an upcoming migration of Polymer elements in pure 2.0 implementation?
Do you recommend to progressively move away from HTML for Web Component development in general?
Cheers,
Pascal

**Comment by surma** [comment]
This project is not going to end up being library. It will be a section on [Web Fundamentals](https://developers.google.com/web/fundamentals), where you can read the densely annotated code. It’s supposed to be an educational resource to learn how to write (or improve) web components that are accessible, performant and JavaScript idiomatic. – not a library that you use.

In general, I recommend preferring native HTML elements over custom built ones. But when you _do_ have to build elements, build ’em right ;)

Hope this answers your question.

**Comment by MeTaNoV** [comment]
@surma, it depends what you means by "build 'em right"! :)

**Comment by robdodson** [comment]
I think the best way to think of this project is similar to Jake Archibald's [Offline Cookbook](https://jakearchibald.com/2014/offline-cookbook/) which shows how to do common things using native, raw service workers. We want to teach how the standards work at the lowest level, and then link out to libraries which make this easier for developers, such as Polymer and SkateJS.

**Comment by MeTaNoV** [comment]
Thanks @robdodson for the confirmation! Back to 2.0! And gr8 job BTW!
